export const TEMPLATES = [
  {
    id: "modern",
    name: "Modern",
    description: "Clean sidebar layout with teal accent",
    color: "from-teal-500/10 to-emerald-500/10",
    borderColor: "hover:border-teal-500/50",
    category: "professional" as const,
    industry: "Technology",
    style: "Modern",
    popularity: 95,
  },
  {
    id: "classic",
    name: "Classic",
    description: "Traditional elegance with serif typography",
    color: "from-slate-500/10 to-gray-500/10",
    borderColor: "hover:border-slate-500/50",
    category: "professional" as const,
    industry: "Finance",
    style: "Professional",
    popularity: 88,
  },
  {
    id: "executive",
    name: "Executive",
    description: "Premium design with monogram accent",
    color: "from-amber-600/10 to-yellow-600/10",
    borderColor: "hover:border-amber-600/50",
    category: "executive" as const,
    industry: "Finance",
    style: "Professional",
    popularity: 82,
  },
  {
    id: "minimalist",
    name: "Minimalist",
    description: "Swiss-inspired clean grid design",
    color: "from-gray-500/10 to-zinc-500/10",
    borderColor: "hover:border-gray-500/50",
    category: "professional" as const,
    industry: "Technology",
    style: "Minimal",
    popularity: 90,
  },
  {
    id: "creative",
    name: "Creative",
    description: "Editorial magazine-style layout",
    color: "from-orange-500/10 to-red-500/10",
    borderColor: "hover:border-orange-500/50",
    category: "creative" as const,
    industry: "Creative",
    style: "Creative",
    popularity: 78,
  },
  {
    id: "technical",
    name: "Technical",
    description: "Dark IDE-inspired developer theme",
    color: "from-blue-600/10 to-cyan-600/10",
    borderColor: "hover:border-blue-600/50",
    category: "technical" as const,
    industry: "Technology",
    style: "Modern",
    popularity: 85,
  },
  {
    id: "adaptive",
    name: "Smart Template",
    description: "Auto-adapts layout to your content",
    color: "from-indigo-500/10 to-violet-500/10",
    borderColor: "hover:border-indigo-500/50",
    category: "professional" as const,
    industry: "General",
    style: "Adaptive",
    popularity: 100,
  },
  {
    id: "timeline",
    name: "Timeline",
    description: "Visual career journey storytelling",
    color: "from-slate-600/10 to-orange-500/10",
    borderColor: "hover:border-orange-500/50",
    category: "creative" as const,
    industry: "Creative",
    style: "Visual",
    popularity: 92,
  },
  {
    id: "ivy",
    name: "Ivy League",
    description: "Finance & consulting standard format",
    color: "from-slate-600/10 to-zinc-600/10",
    borderColor: "hover:border-slate-600/50",
    category: "professional" as const,
    industry: "Finance",
    style: "Classic",
    popularity: 89,
  },
  {
    id: "ats-clarity",
    name: "Clarity",
    description: "Single-column, ATS-optimized with bold headings and tight spacing",
    color: "from-cyan-500/10 to-blue-500/10",
    borderColor: "hover:border-cyan-500/50",
    category: "professional" as const,
    industry: "General",
    style: "ATS",
    popularity: 91,
  },
  {
    id: "ats-structured",
    name: "Structured",
    description: "Strict grid, left-aligned labels, and parser-safe typography",
    color: "from-emerald-500/10 to-green-500/10",
    borderColor: "hover:border-emerald-500/50",
    category: "professional" as const,
    industry: "Technology",
    style: "ATS",
    popularity: 88,
  },
  {
    id: "ats-compact",
    name: "Compact",
    description: "Condensed layout for early-career roles and quick scans",
    color: "from-purple-500/10 to-indigo-500/10",
    borderColor: "hover:border-purple-500/50",
    category: "professional" as const,
    industry: "General",
    style: "ATS",
    popularity: 86,
  },
] as const;

export type TemplateId = (typeof TEMPLATES)[number]["id"];

// Export as 'templates' for compatibility
export const templates = TEMPLATES;
